### ISSUE TITLE
Error: no such table: pragma_table_info

### ISSUE THREAD

**Issue by derdershat** [mintsoft/kodi.plugin.ytchannels#13]
Hi,

I normally use your ytchannels addon but now I get an addon error

I am on Kodi 18.8 (Windows)

2020-09-27 20:12:15.211 T:5372   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'sqlite3.OperationalError'>
                                            Error Contents: no such table: pragma_table_info
                                            Traceback (most recent call last):
                                              File "C:\Kodi Leia\portable_data\addons\plugin.video.ytchannels\default.py", line 4, in <module>
                                                ytchannels_main()
                                              File "C:\Kodi Leia\portable_data\addons\plugin.video.ytchannels\resources\lib\ytchannels.py", line 53, in ytchannels_main
                                                SORT_INIT = check_sort_db()
                                              File "C:\Kodi Leia\portable_data\addons\plugin.video.ytchannels\resources\lib\functions.py", line 87, in check_sort_db
                                                cur.execute("SELECT 1 FROM pragma_table_info('Channels') WHERE name = 'sort';")
                                            OperationalError: no such table: pragma_table_info
                                            -->End of Python script error report<--
2020-09-27 20:12:15.260 T:11772   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ytchannels/
2020-09-27 20:12:15.260 T:11304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ytchannels/) failed

**Comment by mintsoft** [comment]
@derdershat interesting, is that since upgrading to 0.3.1 (released this weekend)?

**Comment by mintsoft** [comment]
@derdershat I can't reproduce this, from the error it looks like the version of SQLLite used isn't right. Is this the 18.8 release downloadable from here: https://kodi.tv/download or has it been compiled differently?

**Comment by yeahme49** [comment]
@derdershat I can't reproduct this either. What version of ytchannels are you using? When did the error start occuring, after a plugin update or after a Kodi update?

**Comment by derdershat** [comment]
Hi,

I use YouTube Channels version= 0.3.1  
installed from official repo + downloaded from here 

I tried it again with a fresh installed Kodi 18.8 32bit (downloaded from https://kodi.tv/download) on my Windows 10 PC and got the same error...

here a full log 
[https://pastebin.com/fPgDfjTf](url)

I checked the sqlite3.dll but have no version detail ... date is from 05.02.2016  or do you mean the python sqlite3?

**Comment by yeahme49** [comment]
Ok I figured it out.

I was getting 3.26 for the sqlite version from https://github.com/xbmc/xbmc/tree/Leia/tools/depends/target/sqlite3. I'm not sure what that is used for, maybe Linux versions. But on Windows it uses https://github.com/xbmc/xbmc/tree/Leia/project/BuildDependencies/scripts to download the proper files. Leia 32-bit is using 3.10.2 which is not new enough. Leia 64-bit uses 3.17.0, not sure why they are such different versions.

I will test my alternate way of checking for the column and submit a pull request today.

**Comment by derdershat** [comment]
thank you very much, your changes in functions.py works here

**Comment by mintsoft** [comment]
Aha, that explains it 👍
