### ISSUE TITLE
Unable to delete channels with version 0.3.3

### ISSUE THREAD

**Issue by gittest598** [mintsoft/kodi.plugin.ytchannels#18]
Hi, this problem happens on Kodi 18.9 and 19.0 on Windows portable install, when I try to delete any channel a error message pops up saying Youtube Channels error Check log for information. I can delete a Folder just not the channels in side. If I re add the deleted folder add a channel in it, I still can't delete it. I have posted the error log below which was on Kodi 18.9 but it also happens on 19.0. 

2021-04-09 09:59:44.589 T:2092 WARNING: Attempt to use invalid handle -1
2021-04-09 09:59:44.602 T:2092   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: change_folder() takes exactly 2 arguments (1 given)
                                            Traceback (most recent call last):
                                              File "E:\KODI backup\Kodi\portable_data\addons\plugin.video.ytchannels\default.py", line 4, in <module>
                                                ytchannels_main()
                                              File "E:\KODI backup\Kodi\portable_data\addons\plugin.video.ytchannels\resources\lib\ytchannels.py", line 345, in ytchannels_main
                                                change_folder(channel_id)
                                            TypeError: change_folder() takes exactly 2 arguments (1 given)
                                            -->End of Python script error report<--

**Comment by mintsoft** [comment]
Thanks for the report, I'll take a look!

**Comment by mintsoft** [comment]
This is fixed in 0.3.4; just waiting for merge of: https://github.com/xbmc/repo-plugins/pull/3541 https://github.com/xbmc/repo-plugins/pull/3542 and then it should be released
